image: eclipse-temurin:21

stages:
  - build
  - package
  - helmchart
  - changelog

include:
  - remote: 'https://gitlab.com/g3476/cliffhanger/-/raw/main/gitlab-ci/cliffhanger.yml'

buildTgz:
  tags:
    - glubo
  only:
    - tags
  stage: build
  variables:
    TARGET_JS: true
  script:
    - ./gradlew kotlinUpgradeYarnLock
    - ./gradlew jsBrowserDistribution
    - tar -czf plumbeteer.tgz -C build/dist/js/productionExecutable/ .
  artifacts:
    paths:
      - plumbeteer.tgz
    expire_in: 1 days

buildDocker:
  tags:
    - glubo
  only:
    - tags
  stage: package
  image: gcr.io/kaniko-project/executor:v1.14.0-debug

  script:
    - ls
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

buildHelm:
  tags:
    - glubo
  only:
    - tags
  stage: helmchart
  image: alpine/helm
  script:
    - helm plugin install https://github.com/chartmuseum/helm-push
    - helm package helm/plumbeteer --version "${CI_COMMIT_REF_NAME}" --app-version "${CI_COMMIT_REF_NAME}"
    - echo helm repo add --username PRIVATE-TOKEN --password "${NYX_TOKEN}" gitlab "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/main"
    - helm repo add --username PRIVATE-TOKEN --password "${NYX_TOKEN}" gitlab "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/main"
    - helm repo list
    - helm cm-push "plumbeteer-${CI_COMMIT_REF_NAME}.tgz" gitlab

buildIos:
  tags:
    - saas-macos-medium-m1
  image: macos-15-xcode-16
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
    - when: never
  variables:
    TARGET_IOS: true
  script:
    - asdf list all java
    - asdf install java openjdk-21
    - asdf local java openjdk-21
    - ./gradlew --version
    - asdf list
    #- ./gradlew packageIosDeviceRelease
    - ./gradlew linkReleaseFrameworkIosArm64
    - ls --tree build/platforms/ios
    - cp -r ios.template/* build/platforms/ios/
    - cd build/platforms/ios/
    - gem install fastlane --no-document
    - fastlane beta
  #cache:
    #- paths:
      #- build
